[ids]

*

[main]

# click for esc, hold for nav
capslock = overload(nav, esc)

# swap control and meta(super)
leftcontrol = layer(meta)
leftmeta = layer(control)
esc = `

[control]
space = macro(leftmeta+leftalt+space)

[nav:M]
# only works when capslock is holding

# vim style navigation
h = left
j = down
k = up
l = right

a = home
e = end
d = delete
y = backspace

b = macro(leftcontrol+b)

# space = macro(leftcontrol+space)

# f = macro(leftmeta+leftalt+f)
# v = macro(leftmeta+leftalt+v)
# t = macro(leftmeta+leftalt+t)
# i = macro(leftmeta+leftalt+i)
# m = macro(leftmeta+leftalt+m)
# p = macro(leftmeta+leftalt+p)

[meta]

space = macro(leftmeta+leftalt+space)
