[ids]

*

[main]

# click for esc, hold for nav
leftcontrol = overload(nav, esc)

# swap control and meta(super)
leftmeta = layer(control)

esc = `

[control]
space = macro(leftmeta+leftalt+space)

[nav:M]
# only works when control is holding

# vim style navigation
h = left
j = down
k = up
l = right

a = home
e = end
d = delete
y = backspace

b = macro(leftcontrol+b)

[meta]
space = macro(leftmeta+leftalt+space)
