return {
    {
        "mason-org/mason.nvim",
        opts = {
            ensure_installed = {
                "bash-language-server",
                "beautysh",
                "biome",
                "codelldb",
                "css-lsp",
                "debugpy",
                "docker-compose-language-service",
                "dockerfile-language-server",
                "hadolint",
                "html-lsp",
                "js-debug-adapter",
                "json-lsp",
                "lua-language-server",
                "markdown-toc",
                "markdownlint-cli2",
                "marksman",
                "prettier",
                "pyright",
                "ruff",
                "rust-analyzer",
                "shellcheck",
                "shfmt",
                "sqlfluff",
                "stylua",
                "tailwindcss-language-server",
                "taplo",
                "vtsls",
                "yaml-language-server",
            },
        },
    },
}
